---
App\Entity\User:
  attributes:
    normalization_context:
      groups: ['user:read']
    # denormalization_context:
    #   groups: ['user:write']
    input: App\DTO\UserInput
    output: App\DTO\UserOutput
  collectionOperations: ~
  itemOperations:
    get: ~
    patch: ~
    delete: ~