---
App\Entity\User:
  constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
  properties:
    name:
      - NotBlank: ~
    email:
      - NotBlank: ~
      - Email: ~

App\Entity\Product:
  constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
  properties:
    name:
      - NotBlank: ~
